// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJvvjl81XnuPnyMi4mJ-33Fvvo3Red1FI',
    appId: '1:646074818132:android:6ff126584042a670fb17c1',
    messagingSenderId: '646074818132',
    projectId: 'nutritionapp-6a26b',
    storageBucket: 'nutritionapp-6a26b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8hnbQmQZ9PZ6Fvrxe9ZfvrVULziXCFeI',
    appId: '1:646074818132:ios:d407d26513a6b5e7fb17c1',
    messagingSenderId: '646074818132',
    projectId: 'nutritionapp-6a26b',
    storageBucket: 'nutritionapp-6a26b.appspot.com',
    androidClientId: '646074818132-08vlpmf4n5i9mmel0mq74b04pmponfo6.apps.googleusercontent.com',
    iosClientId: '646074818132-4tokqoce2l2sej58r21n4rjanic1dofr.apps.googleusercontent.com',
    iosBundleId: 'com.nutritionapps.aiNutritionTracker',
  );

}